### ISSUE TITLE
JSX Spread operator throws syntax error

### ISSUE THREAD

**Issue by zovt** [mooz/js2-mode#351] opened 2016-07-05 17:10 UTC
for example:

```
const x = this.someArray.map((props) => <Component {...props} />);
```

**Comment by Wilfred** [comment] 2016-08-18 17:16
The object spread operator was released in 0cda39255827f283e7578cd469ae42daad9556a2 (version 20160623), and added in 2a904e08fe3e009409ccfb8f928fab43f7efaeed.

It's not clear to me which parts of the parser are JSX related and need to be updated.

**Comment by dgutov** [comment] 2016-08-26 23:46
It seems like this would require us to support JS syntax like this first:

```js
var b = ...c;
```

Is there some ESn proposal like this? Can this even make sense?

Alternatively, we'd have to parse interpolated expressions inside XML literals like functions parameters..?

**Comment by Wilfred** [comment] 2016-08-29 01:50
> Is there some ESn proposal like this?

`...` is supported in the following situations:

[rest parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters), e.g. `function foo(x, y, ...more) { whatever() }`

[spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) e.g. `[...iterableObj, 4, 5, 6]` and `myFunction(-1, ...args, 2, ...[3]);` and `var foo = [...bar]`

[destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) e.g. `({a, b, ...rest} = {a:1, b:2, c:3, d:4}); `

So your example doesn't make sense, but you can use `...` in an awful lot of contexts.

**Comment by dgutov** [comment] 2016-08-29 08:56
Yes. Too mad E4X doesn't interpret `{ ... }` like one of those contexts.

**Comment by Wilfred** [comment] 2016-08-30 15:12
> Alternatively, we'd have to parse interpolated expressions inside XML literals like functions parameters..?

Would there be any downsides to doing this? I'm not familiar with the js2-mode code.

**Comment by dgutov** [comment] 2016-08-30 18:17
It will likely break E4X support, to some extent. Which is the (outdated) technology we actually support, not JSX.

**Comment by aaronjensen** [comment] 2016-09-28 11:11
fwiw `{...props}` is a jsx specific construct. It exists and is usable even in situations where object rest and object spread is not available.

**Comment by Wilfred** [comment] 2016-11-12 23:49
It looks like https://github.com/felipeochoa/rjsx-mode has solved this problem.

**Comment by zovt** [comment] 2017-05-03 17:47
is this still a problem in this package? is the suggested rjsx-mode the fix? If so, I can close this issue as wontfix

**Comment by ibrahima** [comment] 2017-11-22 20:38
I can confirm that using rjsx-mode (which extends js2-mode) fixes this issue, so this can probably be closed.

**Comment by dgutov** [comment] 2017-11-22 21:17
Yeah, ok. 😃

**Closed by dgutov** 2017-11-22 21:17 UTC
Labels: wontfix
