### ISSUE TITLE
Indentation bounces around while typing with bounce indent

### ISSUE THREAD

**Issue by PythonNut** [mooz/js2-mode#244] opened 2015-06-22 01:15 UTC
No, this is not a joke. I honestly don't know how to say it better.

**Steps to reproduce**

1. `emacs -Q`
2. <kbd>M-x</kbd> <kbd>package-initialize</kbd>
3. <kbd>C-x</kbd> <kbd>b</kbd> <kbd>test</kbd> <kbd>M-x</kbd> <kbd>js2-mode</kbd>
4. Type this:
```js
(function () {
    return true;
});
```

**What is expected**
```js
(function () {
    return true;
});
```

**What actually happens**
```js
(function () {
return true;
    });
```
Note how the indentations bounces on typing parens and semicolons, which generally leads to incorrect indentation.

**Comment by dgutov** [comment] 2015-06-22 09:48
It's a duplicate of #226.

**Closed by dgutov** 2015-06-22 09:48 UTC
