### ISSUE TITLE
js2-mode does not understand default values in destructuring assignments

### ISSUE THREAD

**Issue by cjohansen** [mooz/js2-mode#240] opened 2015-06-03 07:57 UTC
```js
const {style, p=progress} = progress;

// If progress = 32, then style === undefined, p === 32
// If progress = {progress: 32, style: 'yellow'}, then style === 'yellow', p === 32
```

js2-mode flags this snippet as a syntax error, as it doesn't know about the use of `=` in the destructuring assignment for default values.

Here's Firefox's discussion of their support: https://bugzilla.mozilla.org/show_bug.cgi?id=932080

**Comment by dgutov** [comment] 2015-06-03 13:52
Thanks for the Bugzilla link, but this issue is a duplicate of #205.

**Closed by dgutov** 2015-06-03 13:52 UTC

**Comment by cjohansen** [comment] 2015-06-03 13:54
Sorry, that's very sloppy of me. I even looked at the issue list, but failed to spot it...
